/**/*:
  ros__parameters:
    broker:
      host: localhost
      port: 1883
    bridge:
      # ROS to MQTT bridge
      ros2mqtt:
        ros_topics:
          - /mqtt_out
        /mqtt_out:
          mqtt_topic: /mqtt_out
          primitive: true
          ros_type: std_msgs/msg/String
          # advanced:
          #   ros:
          #     queue_size: 10
          #     qos:
          #       durability: auto
          #       reliability: auto
          
      # MQTT to ROS bridge          
      mqtt2ros:
        mqtt_topics:
          - mqtt_in
        mqtt_in:
          ros_topic: /mqtt_in
          primitive: true
          ros_type: std_msgs/msg/Int32
          # advanced:
          #   ros:
          #     queue_size: 10
          #     qos:
          #       durability: transient_local
          #       reliability: reliable
